### ISSUE TITLE
Add a logo for Decode this

### ISSUE THREAD

**Issue by notthetup** [notthetup/decodethis#2]
Add logo on main page as well as a favicon.

**Comment by sayanee** [comment]
:thumbsup:

**Comment by sayanee** [comment]
1. **favicon**
   
   ![image](https://cloud.githubusercontent.com/assets/413879/4333266/9d701308-3fde-11e4-8579-5df3d9e81a11.png)
2. **logo on desktop**
   
   ![image](https://cloud.githubusercontent.com/assets/413879/4333272/a94d06ae-3fde-11e4-9061-289140770986.png)
3. **logo on mobile vertical**
   
   ![photo 19-9-14 5 24 05 pm](https://cloud.githubusercontent.com/assets/413879/4333291/d88a44b8-3fde-11e4-8ea9-97e2856c5acf.png)
4. **logo on mobile horizontal**
   
   ![photo 19-9-14 5 24 25 pm](https://cloud.githubusercontent.com/assets/413879/4333292/d88d6fda-3fde-11e4-9bc1-3ae8daa08780.png)
5. **apple touch icon**
   
   ![photo 19-9-14 5 40 58 pm](https://cloud.githubusercontent.com/assets/413879/4333501/31e16fe4-3fe1-11e4-835c-e64162aa19f7.png)

**Comment by notthetup** [comment]
Yay!! Thanks <3!
